### ISSUE TITLE
对象数组内部值获取报错

### ISSUE THREAD

**Issue by YujiaCheng1996** [fuchengwei/element-plus-readonly-form-item#1]
源码中的getValue过于简单，导致动态对象数组内部属性获取时报错。
// 源码const getValue = () => (attrs.prop as string)?.split('.')?.reduce((pre, cur) => pre[cur], elFormModel.value)
表单数据：
`const form = ref({arr:[{a:1},{a:2}]});`
外层：
`v-for="(_,index) in form" :key="index"`
内层：
```
          <readonly-form-item :prop="`arr.${index}.a`">
                      <el-input v-model="form.arr[index].a"></el-input>
          </readonly-form-item>
```
当操作数组（增删数量）时报错：如 `form.value.arr.splice(0,1)`
`Uncaught TypeError: Cannot read properties of undefined (reading 'a')`
另外prop也不支持：`arr[${index}].a`这样的绑定

**Comment by fuchengwei** [comment]
这里的外层为什么循环的是 form 呢 不是应该循环 arr 吗

**Comment by fuchengwei** [comment]
已修复 升级 1.2.1 即可。

**Comment by YujiaCheng1996** [comment]
那个是form.arr，写错了。感谢，用了这个组件少写一半代码！

**Comment by fuchengwei** [comment]
> 那个是form.arr，写错了。感谢，用了这个组件少写一半代码！

感谢肯定
