### ISSUE TITLE
有关vue3+element plus 使用element-plus-readonly-form-item单选框产生的问题，

### ISSUE THREAD

**Issue by xxy-code** [fuchengwei/element-plus-readonly-form-item#2]
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/3e4a6a4d-d270-4ec8-8e44-67c59cf9c398)
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/711fc3b1-c7fb-4e30-bd0f-27cc3452e7fe)
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/ddd5364d-6b0f-45ab-a5c5-fdc29050aa3f)
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/70e67ae9-4368-44d2-86b8-a091bc437b88)
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/f5f801aa-c097-4e7f-b806-a3b8ce3ac0ef)

**Comment by fuchengwei** [comment]
可以提供一个最小的可以复现的项目和数据发到我的邮箱吗 1572060320@qq.com

**Comment by xxy-code** [comment]
我昨天有尝试修改了一下，我原来代码是这个样子
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/d634e58f-39e9-4d85-841f-78095b980839)
修改为一面这样就可以了。
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/0dfc264c-8647-4364-b884-89ba85e8081c)
const rvIsvalidOptions = [ {    value: 'Y',    label: '是',  },  {    value: 'N',    label: '否',  },]
下拉框也是同样的问题，应该是不兼容这样写吧，谢谢大大

**Comment by xxy-code** [comment]
大大，其实还有一个问题，就是向用户角色和企业。那里其实是两个下拉框，然后我传进来的应该是value，去匹配，然后展示label才对，但现在是直接展示了value。

**Comment by fuchengwei** [comment]
> 

这个问题 我排查一下

**Comment by fuchengwei** [comment]
> 大大，其实还有一个问题，就是向用户角色和企业。那里其实是两个下拉框，然后我传进来的应该是value，去匹配，然后展示label才对，但现在是直接展示了value。

这个可以举个🌰吗 你传进来的 value 指哪个 value ？

**Comment by xxy-code** [comment]
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/0b44df8c-c78a-4c8e-becf-ef72b45c1e46)
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/0169416a-a469-434b-93c1-ddb779a24a8b)

**Comment by xxy-code** [comment]
我是把共用下拉框，都封装成了组件

**Comment by fuchengwei** [comment]
> 我是把共用下拉框，都封装成了组件

我刚看了你的代码 你是用你的公共组件不能回显吗？你把 prop 写成和 v-model 的值一样试试呢 usrRoleVo

**Comment by xxy-code** [comment]
好的，我试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月13日 10:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [fuchengwei/element-plus-readonly-form-item] 有关vue3+element plus 使用element-plus-readonly-form-item单选框产生的问题， (Issue #2) |

我是把共用下拉框，都封装成了组件

我刚看了你的代码 你是用你的公共组件不能回显吗？你把 prop 写成和 v-model 的值一样试试呢 usrRoleVo

**Comment by xxy-code** [comment]
> 我刚看了你的代码你用你的公共组件不能回显吗？你把 prop 写成和 v-model 的值一样试试呢 usrRoleVo
大大，这样不可以。。。没有效果

**Comment by fuchengwei** [comment]
> > 我刚看了你的代码你用你的公共组件不能回显吗？你把 prop 写成和 v-model 的值一样试试呢 usrRoleVo
> > 大大，这样不可以。。。没有效果

贴一下你的代码 还有上层的 el-form 是怎么写的

**Comment by xxy-code** [comment]
`      <el-form  :model="formDetail" label-width="120px" ref="dialogFormRef" :rules="rules" :readonly="fromReadOnly" :key="key">
        <el-row >
          <el-col :span="8">
            <readonly-form-item label="用户代码：" prop="userName">
              <el-input v-model="formDetail.userName" placeholder="请输入" clearable maxlength="16" :disabled = fromDisabled />
            </readonly-form-item>
          </el-col>
          <el-col :span="8">
            <readonly-form-item label="用户名称：" prop="nickName">
              <el-input v-model="formDetail.nickName" placeholder="请输入" clearable maxlength="32"/>
            </readonly-form-item>
          </el-col>
          <el-col :span="8">
              <readonly-form-item label="用户状态：" prop="enabled">
                  <el-select v-model="formDetail.enabled" filterable clearable  placeholder="请选择" style="width: 100%">
                      <el-option v-for="item in enabledOptions" :key="item.value" :label="item.label" :value="item.value"  />
                  </el-select>
              </readonly-form-item>
          </el-col>
        </el-row>
        <el-row >
          <el-col :span="8">
            <readonly-form-item label="用户角色：" prop="usrRole">
               <sys-role-select :key="formDetail.id" :roles="roles" v-model="formDetail.usrRoleVo" @getRoles="getRoles" style="width: 100%"/>
            </readonly-form-item>
          </el-col>
            <el-col :span="8">
                <readonly-form-item label="企业：" prop="enterpriseCode">
                    <company-select :key="formDetail.id" v-model="formDetail.enterpriseCode" style="width: 100%"/>
                </readonly-form-item>
            </el-col>
          <el-col :span="8">
            <readonly-form-item label="用户部门：" >
              <el-input v-model="formDetail.usrDepart" clearable placeholder="请输入" maxlength="16"/>
            </readonly-form-item>
          </el-col>
        </el-row>
        <el-row >
          <el-col :span="8">
            <readonly-form-item label="联系电话：" prop="mobile">
              <el-input v-model="formDetail.mobile" clearable placeholder="请输入" maxlength="11"/>
            </readonly-form-item>
          </el-col>
          <el-col :span="8">
            <readonly-form-item label="用户邮箱：" prop="usrEmail">
              <el-input v-model="formDetail.usrEmail" clearable placeholder="请输入" maxlength="16"/>
            </readonly-form-item>
          </el-col>
        </el-row>
        <el-row >
          <el-col :span="24">
            <readonly-form-item label="备注：" >
              <el-input v-model="formDetail.memo" clearable type="textarea"  placeholder="请输入" :autosize="{ minRows: 4, maxRows: 6 }" maxlength="100"/>
            </readonly-form-item>
          </el-col>
        </el-row>
        <el-row >
          <el-col :span="24" align="center">
            
              <el-button v-if="viewEdit" type="primary" @click="updateUserDetail(dialogFormRef)" plain>保存</el-button>
              <el-button @click="closeDialog(dialogFormRef)">关闭</el-button>
            
          </el-col>
        </el-row>
      </el-form>`

**Comment by xxy-code** [comment]
`      <el-form  :model="formDetail" label-width="120px" ref="dialogFormRef" :rules="rules" :readonly="fromReadOnly" :key="key">  
        <el-row >  
          <el-col :span="8">  
            <readonly-form-item label="用户代码：" prop="userName">
              <el-input v-model="formDetail.userName" placeholder="请输入" clearable maxlength="16" :disabled = fromDisabled />
            </readonly-form-item>
          </el-col>
          <el-col :span="8">
            <readonly-form-item label="用户名称：" prop="nickName">
              <el-input v-model="formDetail.nickName" placeholder="请输入" clearable maxlength="32"/>
            </readonly-form-item>
          </el-col>
          <el-col :span="8">
              <readonly-form-item label="用户状态：" prop="enabled">
                  <el-select v-model="formDetail.enabled" filterable clearable  placeholder="请选择" style="width: 100%">
                      <el-option v-for="item in enabledOptions" :key="item.value" :label="item.label" :value="item.value"  />
                  </el-select>
              </readonly-form-item>
          </el-col>
        </el-row>
        <el-row >
          <el-col :span="8">
            <readonly-form-item label="用户角色：" prop="usrRole">
               <sys-role-select :key="formDetail.id" :roles="roles" v-model="formDetail.usrRoleVo" @getRoles="getRoles" style="width: 100%"/>
            </readonly-form-item>
          </el-col>
            <el-col :span="8">
                <readonly-form-item label="企业：" prop="enterpriseCode">
                    <company-select :key="formDetail.id" v-model="formDetail.enterpriseCode" style="width: 100%"/>
                </readonly-form-item>
            </el-col>
          <el-col :span="8">
            <readonly-form-item label="用户部门：" >
              <el-input v-model="formDetail.usrDepart" clearable placeholder="请输入" maxlength="16"/>
            </readonly-form-item>
          </el-col>
        </el-row>
        <el-row >
          <el-col :span="8">
            <readonly-form-item label="联系电话：" prop="mobile">
              <el-input v-model="formDetail.mobile" clearable placeholder="请输入" maxlength="11"/>
            </readonly-form-item>
          </el-col>
          <el-col :span="8">
            <readonly-form-item label="用户邮箱：" prop="usrEmail">
              <el-input v-model="formDetail.usrEmail" clearable placeholder="请输入" maxlength="16"/>
            </readonly-form-item>
          </el-col>
        </el-row>
        <el-row >
          <el-col :span="24">
            <readonly-form-item label="备注：" >
              <el-input v-model="formDetail.memo" clearable type="textarea"  placeholder="请输入" :autosize="{ minRows: 4, maxRows: 6 }" maxlength="100"/>
            </readonly-form-item>
          </el-col>
        </el-row>
        <el-row >
          <el-col :span="24" align="center">
            
              <el-button v-if="viewEdit" type="primary" @click="updateUserDetail(dialogFormRef)" plain>保存</el-button>
              <el-button @click="closeDialog(dialogFormRef)">关闭</el-button>
          </el-col>
        </el-row>
      </el-form>`

**Comment by xxy-code** [comment]
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/e6da4a64-fecc-4234-af49-f6c3b6d90ae0)

**Comment by fuchengwei** [comment]
> ![image](https://user-images.githubusercontent.com/63041889/267520911-e6da4a64-fecc-4234-af49-f6c3b6d90ae0.png)

我看你的 prop 也没有修改啊 你的 prop 不是还写的 usrRole

**Comment by xxy-code** [comment]
改了之后就彻底不展示了
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/826fb2ce-145f-418d-993c-89fd652c6a4b)
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/f2005690-dbf5-4cd5-9976-de88a7b2cf68)
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/06c63dfb-6f42-45ae-8e19-3a4a4ff4bd34)

**Comment by xxy-code** [comment]
而且企业那的prop是和v-model是一致的，也是没有效果的

**Comment by fuchengwei** [comment]
那看来 vue3 的这个对于自定义组件支持还是有一些问题 可以考虑用 value 属性传入显示的值

**Comment by xxy-code** [comment]
这是对应的用户角色
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/ce646835-5c85-4198-9fd7-441bf404cad6)
这是对应的企业
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/c0bff82e-03e1-4059-82d5-3063876e7cf7)

**Comment by fuchengwei** [comment]
> 这是对应的用户角色 ![image](https://user-images.githubusercontent.com/63041889/267523583-ce646835-5c85-4198-9fd7-441bf404cad6.png) 这是对应的企业 ![image](https://user-images.githubusercontent.com/63041889/267523673-c0bff82e-03e1-4059-82d5-3063876e7cf7.png)

后面我有时间研究一下吧 可以先使用 value 保证显示的正常

**Comment by xxy-code** [comment]
![image](https://github.com/fuchengwei/element-plus-readonly-form-item/assets/63041889/e2b21ccf-932c-4333-8b0b-099d8bcb0ca8)
为什么这个children会是空的？是我的子组件的写法不对吗

**Comment by fuchengwei** [comment]
> ![image](https://user-images.githubusercontent.com/63041889/267557761-e2b21ccf-932c-4333-8b0b-099d8bcb0ca8.png) 为什么这个children会是空的？是我的子组件的写法不对吗

这个不太清楚 需要根据你写的内容 打断点排查一下
