### ISSUE TITLE
 出现警告：[Vue warn]: injection "Symbol(formContextKey)" not found.

### ISSUE THREAD

**Issue by xiongchencheng** [fuchengwei/element-plus-readonly-form-item#3]
我这边总是出现 这样的警告，使用的就是你这里给到的事例代码

**Comment by xiongchencheng** [comment]
![Uploading Snipaste_2023-11-17_10-40-49.png…]()

**Comment by xiongchencheng** [comment]
"element-plus": "^2.2.21",
 "element-plus-readonly-form-item": "^1.11.0"
这是我目前使用的版本信息

**Comment by fuchengwei** [comment]
我刚去验证了一下 这个你升级最新的 element-plus 版本就好了 应该是低版本的 element-plus 没有导出这个常量Symbol(formContextKey)

**Comment by YujiaCheng1996** [comment]
目前最新版的element-plus还存在这个问题
